<script setup lang="ts">
import HotelCard from "./HotelCard.vue";
// This would typically come from an API or database
const mockHotels = [
  {
    id: "1",
    name: "Luxury Resort & Spa",
    image: "/hotel1.jpg",
    rating: 4.5,
    price: 250,
    location: "Maldives",
    description: "Experience luxury and relaxation in our beachfront resort.",
  },
  {
    id: "2",
    name: "City Center Hotel",
    image: "/hotel2.jpg",
    rating: 4.2,
    price: 150,
    location: "New York",
    description: "Stay in the heart of the city that never sleeps.",
  },
  {
    id: "3",
    name: "Mountain Retreat",
    image: "/hotel3.jpg",
    rating: 4.8,
    price: 300,
    location: "Swiss Alps",
    description: "Escape to the mountains for a peaceful and scenic getaway.",
  },
  {
    id: "4",
    name: "Beachside Paradise",
    image: "/hotel4.jpg",
    rating: 4.7,
    price: 275,
    location: "Hawaii",
    description: "Unwind in a tropical paradise by the beach.",
  },
  {
    id: "5",
    name: "Historic Charm Inn",
    image: "/hotel5.jpg",
    rating: 4.3,
    price: 120,
    location: "Charleston",
    description: "Step back in time with our historic and charming inn.",
  },
  {
    id: "6",
    name: "Eco-Friendly Escape",
    image: "/hotel6.jpg",
    rating: 4.6,
    price: 200,
    location: "Costa Rica",
    description: "Relax in an eco-conscious retreat surrounded by nature.",
  },
  {
    id: "7",
    name: "Desert Oasis Resort",
    image: "/hotel7.jpg",
    rating: 4.4,
    price: 220,
    location: "Dubai",
    description: "Luxury in the middle of the desert with breathtaking views.",
  },
  {
    id: "8",
    name: "Lakeview Lodge",
    image: "/hotel8.jpg",
    rating: 4.1,
    price: 140,
    location: "Lake Tahoe",
    description: "Enjoy stunning lake views and outdoor adventures.",
  },
  {
    id: "9",
    name: "Artisan Boutique Hotel",
    image: "/hotel9.jpg",
    rating: 4.9,
    price: 320,
    location: "Paris",
    description: "Experience art and elegance in our boutique hotel.",
  },
  {
    id: "10",
    name: "Seaside Villa",
    image: "/hotel10.jpg",
    rating: 4.0,
    price: 180,
    location: "Santorini",
    description: "Stay in a villa overlooking the crystal-clear Aegean Sea.",
  },
  {
    id: "11",
    name: "Ski Chalet Deluxe",
    image: "/hotel11.jpg",
    rating: 4.8,
    price: 400,
    location: "Aspen",
    description: "Luxury accommodation with direct access to ski slopes.",
  },
  {
    id: "12",
    name: "Countryside B&B",
    image: "/hotel12.jpg",
    rating: 4.2,
    price: 95,
    location: "Cotswolds",
    description: "Charming countryside bed and breakfast for a relaxing stay.",
  },
  {
    id: "13",
    name: "Jungle Hideaway",
    image: "/hotel13.jpg",
    rating: 4.7,
    price: 260,
    location: "Bali",
    description: "A serene retreat surrounded by lush jungle greenery.",
  },
  {
    id: "14",
    name: "Urban Luxury Suites",
    image: "/hotel14.jpg",
    rating: 4.5,
    price: 230,
    location: "Tokyo",
    description: "Modern suites in the heart of a bustling metropolis.",
  },
  {
    id: "15",
    name: "Mediterranean Bliss",
    image: "/hotel15.jpg",
    rating: 4.6,
    price: 210,
    location: "Barcelona",
    description: "Relax and enjoy the Mediterranean sun and culture.",
  },
  {
    id: "16",
    name: "Safari Lodge",
    image: "/hotel16.jpg",
    rating: 4.9,
    price: 450,
    location: "Serengeti",
    description: "Stay close to nature with our luxurious safari lodge.",
  },
  {
    id: "17",
    name: "Clifftop Retreat",
    image: "/hotel17.jpg",
    rating: 4.4,
    price: 290,
    location: "Amalfi Coast",
    description: "Enjoy breathtaking views from our clifftop property.",
  },
  {
    id: "18",
    name: "Riverfront Cabins",
    image: "/hotel18.jpg",
    rating: 4.3,
    price: 110,
    location: "Colorado",
    description: "Rustic cabins with stunning riverfront views.",
  },
  {
    id: "19",
    name: "Island Dream Resort",
    image: "/hotel19.jpg",
    rating: 4.7,
    price: 330,
    location: "Bahamas",
    description: "An island resort offering relaxation and endless blue seas.",
  },
  {
    id: "20",
    name: "Modern City Suites",
    image: "/hotel20.jpg",
    rating: 4.2,
    price: 180,
    location: "Singapore",
    description:
      "Contemporary suites with all the amenities in the city center.",
  },
];
</script>
<template>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <HotelCard v-for="hotel in mockHotels" :key="hotel.id" :hotel="hotel" />
  </div>
</template>
